### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by YonatanKra** [YonatanKra/firebase-functions-scaffolder#5]
- [ ] dbHandler
- [ ] responseHandler
- [ ] test commands in package.json
- [x] support vanilla JS
- [ ] Enable auto insertion into `index.js` (with guidelines)
